config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'couriers/index'

  resources :couriers do
    resources :packages
  end

  root 'couriers#index'
end

app/models/application_record.rb
# frozen_string_literal: true

#:nodoc: all
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
# frozen_string_literal: true

# Represents a single courier.
class Courier < ApplicationRecord
  has_many :packages, dependent: :destroy
  validates :name, presence: true, length: { minimum: 5 }
end

app/models/package.rb
# frozen_string_literal: true

# Represents a single package.
class Package < ApplicationRecord
  belongs_to :courier
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
# frozen_string_literal: true

#:nodoc: all
class CouriersController < ApplicationController
  def index
    @couriers = Courier.all
  end

  def show
    @courier = Courier.find(params[:id])
  end

  def new
    @courier = Courier.new
  end

  def edit
    @courier = Courier.find(params[:id])
  end

  def create
    @courier = Courier.new(courier_params)

    if @courier.save
      redirect_to @courier
    else
      render 'new'
    end
  end

  def update
    @courier = Courier.find(params[:id])

    if @courier.update(courier_params)
      redirect_to @courier
    else
      render 'edit'
    end
  end

  def destroy
    @courier = Courier.find(params[:id])
    @courier.destroy

    redirect_to couriers_path
  end

  private

  def courier_params
    params.require(:courier).permit(:name, :email)
  end
end

app/controllers/packages_controller.rb
# frozen_string_literal: true

#:nodoc: all
class PackagesController < ApplicationController
  def create
    @courier = Courier.find(params[:courier_id])
    @package = @courier.packages.create(package_params)

    redirect_to courier_path(@courier)
  end

  def destroy
    @courier = Courier.find(params[:courier_id])
    @package = @courier.packages.find(params[:id])
    @package.destroy

    redirect_to courier_path(@courier)
  end

  private

  def package_params
    params.require(:package).permit(:tracking_number, :delivery_status)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

#:nodoc: all
module ApplicationHelper; end

app/helpers/couriers_helper.rb
# frozen_string_literal: true

#:nodoc: all
module CouriersHelper; end

app/helpers/packages_helper.rb
# frozen_string_literal: true

#:nodoc: all
module PackagesHelper; end

app/views/couriers/_form.html.erb
<%= form_with model: @courier, local: true, class: 'form' do |form| %>
  <% if @courier.errors.any? %>
    <div class="error-explanation">
      <h3>
        <%= pluralize(@courier.errors.count, "error") %> prohibited this courier from being saved:
      </h3>

      <ul>
        <% @courier.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form__row">
    <%= form.label :name, class: 'form__label' %>
    <%= form.text_field :name %>
  </div>

  <div class="form__row">
    <%= form.label :email, class: 'form__label' %>
    <%= form.text_field :email %>
  </div>

  <div class="form__row">
    <%= button_tag 'Save', class: 'btn btn--stripe' %>
  </div>
<% end %>

app/views/couriers/edit.html.erb
<main>
  <h1>Edit Courier</h1>

  <%= render 'form' %>

  <%= link_to 'Back', couriers_path, class: 'btn btn--stripe btn--back' %>
</main>

app/views/couriers/index.html.erb
<main>
  <h1 class="page__title">Couriers</h1>

  <% if @couriers.any? %>
    <div class="overflow">
      <table>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Actions</th>
        </tr>

        <% @couriers.each do |courier| %>
          <tr>
            <td><%= courier.name %></td>
            <td><%= courier.email %></td>
            <td class="flex"><%= link_to 'Show', courier_path(courier), class: 'btn btn--stripe' %><!--
            --><%= link_to 'Edit', edit_courier_url(courier), class: 'btn btn--stripe' %><!--
            --><%= link_to 'Destroy', courier_path(courier), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn--stripe btn--danger' %></td>
          </tr>
        <% end %>
      </table>
    </div>
  <% else %>
    <p>No couriers yet. Please, add some</p>
  <% end %>

  <%= link_to 'New courier', new_courier_path, class: 'couriers__add btn btn--stripe' %>
</main>

app/views/couriers/new.html.erb
<main>
  <h1>New Courier</h1>

  <%= render 'form' %>

  <%= link_to 'Back', couriers_path, class: 'btn btn--stripe btn--back' %>
</main>

app/views/couriers/show.html.erb
<main>
  <h1>
    <%= @courier.name %>
  </h1>

  <p>
    <%= @courier.email %>
  </p>

  <div class="courier__packages">
    <h2>Packages</h2>

    <% if @courier.packages.any? %>
      <div class="overflow">
        <table>
          <tr>
            <th>Tracking number</th>
            <th>Delivered?</th>
            <th>Actions</th>
          </tr>

          <% @courier.packages.each do |package| %>
            <tr>
              <td><%= package.tracking_number %></td>
              <td><span class="icon icon-<%= package.delivery_status ? 'check' : 'cross' %>"></span></td>
              <td><%= link_to 'Destroy', [package.courier, package], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn--stripe btn--danger' %></td>
            </tr>
          <% end %>
        </table>
      </div>
    <% else %>
      <p>No packages yet. Please, add some</p>
    <% end %>
  </div>

  <%= link_to 'Edit', edit_courier_url(@courier), class: 'btn btn--stripe' %>
  <%= link_to 'Back', couriers_path, class: 'btn btn--stripe btn--back' %>
</main>

<aside class="aside">
  <h2>Add a package:</h2>
  <%= render 'packages/form' %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>DeliveryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap' %>
  </head>

  <body>
    <div class="page">
      <%= yield %>
    </div>
  </body>
</html>